### ISSUE TITLE
make test

### ISSUE THREAD

**Issue by aserebryanskiy** [PrincetonUniversity/FastTemplatePeriodogram#32]
make test failed with error "ImportError: No module named 'nfft'"   . Somehow python code does not sees nfft (pynfft installed)

**Comment by johnh2o2** [comment]
Thanks for bringing this up -- the reason for this is that the `CONDA_INSTALL.md` file is now slightly outdated -- I'm currently working on getting this setup on the pypi repository so that you can just run `pip install ftperiodogram`. I'll let you know when that's finished.

Until then, you should be completely fine by following the conda instructions and adding `pip install nfft` as a last step. We used to use the `pynfft` package, but that's been a bit difficult to install and @jakevdp wrote a nice pure-Python implementation of the NFFT algorithm.

Let us know if that resolves the problem or if you encounter any more difficulties!

**Comment by aserebryanskiy** [comment]
Thanks for the explanation. "make test" run without any problem this time ( 94 passed in 7.75 seconds ) on Intel(R) Core(TM) i5-6600K CPU @ 3.50GHz, Ubuntu 16.04.  And thanks so much for sharing this package!

**Comment by johnh2o2** [comment]
Thanks for the timing datapoint, and I hope the package is of some use to you! Let us know if you encounter any other problems or annoyances, or if you have any suggestions for improvements.

**Comment by johnh2o2** [comment]
OK, install instructions should be fixed as of the first "release" (`v1.0.0`) and simply running
`pip install ftperiodogram` should now install everything correctly.
